# Adapted from https://github.com/ChrisPenner/haskell-stack-travis-ci
language: nix
sudo: true
git:
  depth: 3
  
cache:
    directories:
        - $HOME/.ghc
        - $HOME/.cabal
        - $HOME/.stack
        - .stack-work
        - /nix

matrix:
  fast_finish: true
  include:
    # Add build targets here
    - env: BUILD_BINARY=1
      os: linux
    - env: BUILD_BINARY=1
      os: osx

before_install:
  # Increase the size of ramdisk on sudo enabled infrastructure
  # https://github.com/travis-ci/travis-ci/issues/9036#issuecomment-357189213
  #- sudo mount -o remount,size=50% /var/ramfs
  - rm -Rf $HOME/.ghc $HOME/.cabal $HOME/.stack
  - sudo mkdir -p /etc/nix
  # workaround for a macOS specific issue with trusted users
  - echo "trusted-users = root $USER" | sudo tee -a /etc/nix/nix.conf
  - sudo launchctl kickstart -k system/org.nixos.nix-daemon || true

install:
 - nix-env -if https://github.com/cachix/cachix/tarball/master --substituters https://cachix.cachix.org --trusted-public-keys cachix.cachix.org-1:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSoMckM=
 - cachix use dapp
 - unset CC
 - export PATH=$HOME/.local/bin:$PATH
 - ./.travis/install-ghr.sh

script:
 - df -h
 - nix-env -i stack
 #- echo "$(stack ghc -- --version) [$(stack ghc -- --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - GHC_OPTIONS="-Werror"
 - stack setup || true
 - stack --no-terminal test --ghc-options="$GHC_OPTIONS" || true
 - df -h

after_success:
 - |
   # Build and ship binary
   export BUILD_BINARY=true
   export TRAVIS_TAG=$(git rev-parse HEAD)
   ./.travis/attach-binary.sh

notifications:
  email: false
